class GVAR(RoundStart) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_gamma\showcase_armed_assault\37_MainAssault\showcase_armed_assault_37_mainassault_BHQ_0.ogg", db+5, 1};
};



class GVAR(LeavingCombatArea) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_tank\ta_showcase_tank_destroyers\032_ex_leaving_ao\ta_showcase_tank_destroyers_032_ex_leaving_ao_TDHQ_1.ogg", db+5, 1};
};



class GVAR(SectorCapturing_1) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\30_FriendliesCapturingSector\mp_groundsupport_30_friendliescapturingsector_BHQ_0.ogg", db+5, 1};
};
class GVAR(SectorCapturing_2) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\30_FriendliesCapturingSector\mp_groundsupport_30_friendliescapturingsector_BHQ_1.ogg", db+5, 1};
};
class GVAR(SectorCapturing_3) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\30_FriendliesCapturingSector\mp_groundsupport_30_friendliescapturingsector_BHQ_2.ogg", db+5, 1};
};



class GVAR(SectorCaptured_1) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\40_FriendliesCapturedSector\mp_groundsupport_40_friendliescapturedsector_BHQ_0.ogg", db+5, 1};
};
class GVAR(SectorCaptured_2) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\40_FriendliesCapturedSector\mp_groundsupport_40_friendliescapturedsector_BHQ_1.ogg", db+5, 1};
};
class GVAR(SectorCaptured_3) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\40_FriendliesCapturedSector\mp_groundsupport_40_friendliescapturedsector_BHQ_2.ogg", db+5, 1};
};



class GVAR(SectorLosing_1) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\25_EnemyCapturingSector\mp_groundsupport_25_enemycapturingsector_BHQ_0.ogg", db+5, 1};
};
class GVAR(SectorLosing_2) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\25_EnemyCapturingSector\mp_groundsupport_25_enemycapturingsector_BHQ_1.ogg", db+5, 1};
};
class GVAR(SectorLosing_3) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\25_EnemyCapturingSector\mp_groundsupport_25_enemycapturingsector_BHQ_2.ogg", db+5, 1};
};



class GVAR(SectorLost_1) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\35_EnemyCapturedSector\mp_groundsupport_35_enemycapturedsector_BHQ_0.ogg", db+5, 1};
};
class GVAR(SectorLost_2) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\35_EnemyCapturedSector\mp_groundsupport_35_enemycapturedsector_BHQ_2.ogg", db+5, 1};
};



class GVAR(TicketsLow_Win) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\20_LowTicketsEnemy\mp_groundsupport_20_lowticketsenemy_BHQ_0.ogg", db+5, 1};
};

class GVAR(TicketsLow_Lose) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\15_LowTickets\mp_groundsupport_15_lowtickets_BHQ_0.ogg", db+5, 1};
};



class GVAR(SideDefeated_Win) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_heli\mp_groundsupport\20_LowTicketsEnemy\mp_groundsupport_20_lowticketsenemy_BHQ_2.ogg", db+5, 1};
};
class GVAR(SideDefeated_Lose) : GVAR(Default) {
	sound[] = {"@a3\dubbing_f_epc\c_out2\85_The_End_Of_All_Things\c_out2_85_the_end_of_all_things_BHQ_3.ogg", db+5, 1};
};
