/*
----------------------------------------	COMBAT AREA DATA (INDFOR / RESISTANCE)		----------------------------------------

USAGE:

	1:	Delete everything that's under this comment block
	2:	Paste the output of the exportCombatArea function (should be stored in your clipboard) at the bottom of this file
	3:	Save
	4:	Done!

	*DO NOT ADD ANYTHING ELSE* - NOT EVEN A COMMA (,) OR A SEMICOLON (;) AT THE END OF THE FILE! NOTHING! NYET! NADA!

				vvvvvvv   PASTE ANYWHERE BELOW THIS LINE   vvvvvvv								*/





[[[141.32,93.50],[119.66,12716.09],[12629.21,12706.57],[12707.45,103.68],[-50000.00,-50000.00],[-50000.00,62800.00],[62800.00,62800.00],[62800.00,-50000.00]],[[0.7062,0.7080],[0.7074,-0.7068],[-0.7052,-0.7090],[-0.7096,0.7046]],[[4,0,1],[4,1,5],[5,1,2],[5,2,6],[6,2,3],[6,3,7],[7,3,0],[7,0,4]]]
